name: Build and Deploy from WSL

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted  # Your Windows self-hosted runner
    steps:
      - name: Pull latest and deploy in WSL
        run: |
          wsl -d Ubuntu-22.04 -- bash -ic "
            cd ~/ORV-PametniPaketnik &&
            git pull origin main &&
            chmod +x ./deploy.sh &&
            ./deploy.sh
          "
