name: Build and Push ORV API

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push with Docker Compose
        run: |
          COMMIT_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          docker compose build
          docker tag yourusername/orv-api yourusername/orv-api:latest
          docker tag yourusername/orv-api yourusername/orv-api:$COMMIT_TAG
          docker push yourusername/orv-api:latest
          docker push yourusername/orv-api:$COMMIT_TAG
